name: Alist SDK - Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        alist-version: ['3.28.0', '3.29.0', '3.29.1']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements-dev.txt

    - name: Install AList
      run: bash -ex tests/init_alist.sh
      env:
        ALIST_VERSION: ${{ matrix.alist-version }}

    - name: Run Tests
      run: |
        python -m pytest --log-level=INFO
